apiVersion: apps/v1
kind: Deployment
metadata:
  name: logapp-deployment
  labels:
    app: logapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: logapp-container
        image: saivarma5557/logapp:v1
        ports:
        - containerPort: 7008
